#!/usr/bin/env ruby

# Copyright (C) 2008, 2009 Jeremy Henty.

# This file is part of Ruby-FFI-FLTK1.

# Ruby-FFI-FLTK1 is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Ruby-FFI-FLTK1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


$VERBOSE = true

require "rubygems"
require "ffi/fltk1"

include FFI
include FFI::FLTK

box_width = 100
counter_width = 150
counter_height = 25
window_width = box_width + counter_width
window_height = Counter::TYPES.size * counter_height

Window.new(window_width, window_height, "Counters") do |win|
  Pack.new do |pack|
    pack.widget_type = Pack::Type::VERTICAL
    Counter::TYPES.each do |name, value|
      Pack.new(0, counter_height) do |pack2|
        pack2.widget_type = Pack::Type::HORIZONTAL
        Box.new(box_width, 0, name)
        counter = Counter.new(counter_width, 0)
        counter.widget_type = value
      end
    end
  end
  win.show
end

FLTK.run
