#!/usr/bin/env ruby

# Copyright (C) 2008, 2009 Jeremy Henty.

# This file is part of Ruby-FFI-FLTK1.

# Ruby-FFI-FLTK1 is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Ruby-FFI-FLTK1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


$VERBOSE = true

require "rubygems"
require "ffi/fltk1"

include FFI
include FFI::FLTK

value_height = 25
dial_width = 100
dial_height = 100
box_height = 25
window_width = Dial::TYPES.size * dial_width
window_height =
  value_height + dial_height + box_height

value_format = "%0.2f"

Window.new(window_width, window_height, "Dials") do |win|
  Pack.new do |pack|
    pack.widget_type = Pack::Type::HORIZONTAL
    Dial::TYPES.each do |name, value|
      Pack.new(dial_width, 0) do |pack2|
        pack2.widget_type = Pack::Type::VERTICAL
        value_box = Box.new(0, box_height)
        dial = Dial.new(0, dial_height)
        value_box.label = value_format % [ dial.value ]
        dial.callback { value_box.label = value_format % [ dial.value ] }
        dial.widget_type = value
        Box.new(0, box_height, name)
      end
    end
  end
  win.show
end

FLTK.run
