#!/usr/bin/env ruby

# Copyright (C) 2008, 2009 Jeremy Henty.

# This file is part of Ruby-FFI-FLTK1.

# Ruby-FFI-FLTK1 is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Ruby-FFI-FLTK1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


$VERBOSE = true

require "rubygems"
require "ffi/fltk1"

include FFI
include FFI::FLTK

value_format = "%0.2f"

window_width = window_height = 300

Window.new(window_width, window_height, "Scrollbars") do |win|

  [
   [ Valuator::Type::HORIZONTAL, 20,  0, 280,  20, ],
   [ Valuator::Type::VERTICAL,    0, 20,  20, 280, ],
  ].each do |scrollbar_type, *args|
    scrollbar = Scrollbar.new(*args)
    scrollbar.widget_type = scrollbar_type
    scrollbar.minimum =  0
    scrollbar.maximum = 10
  end

  win.show
end

FLTK.run
