#!/usr/bin/env ruby

# Copyright (C) 2008, 2009 Jeremy Henty.

# This file is part of Ruby-FFI-FLTK1.

# Ruby-FFI-FLTK1 is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Ruby-FFI-FLTK1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


$VERBOSE = true

require "rubygems"
require "ffi/fltk1"

include FFI
include FFI::FLTK

button_classes =
  [
   Button,
   Check_Button,
   Light_Button,
   Repeat_Button,
   Return_Button,
   Round_Button,
   Toggle_Button,
  ]

height = 25
width = 250

Window.new(width, button_classes.size * height, "Buttons") do |win|
  button_classes.each_with_index do |_class,i|
    label = _class.name.gsub(%r{\AFFI::FLTK::}, "")
    button = _class.new(0, i * height, width, height, label)
  end
  win.show
end

FLTK.run
