#!/usr/bin/env ruby

# Copyright (C) 2008, 2009 Jeremy Henty.

# This file is part of Ruby-FFI-FLTK1.

# Ruby-FFI-FLTK1 is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Ruby-FFI-FLTK1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


$VERBOSE = true

require "rubygems"
require "ffi/fltk1"

include FFI
include FFI::FLTK

include MenuItem::Type

Window.new(500, 30, "menubar") do |win|
  menubar = MenuBar.new
  menubar.add("&alpha")
  menubar.add("&beta")
  menubar.add("gamma")
  menubar.add("sub&menu",  nil, nil, nil, SUBMENU)
  menubar.add("submenu/one")
  menubar.add("submenu/two")
  menubar.add("submenu/three")
  menubar.add("inactive",  nil, nil, nil, INACTIVE | DIVIDER)
  menubar.add("invisible", nil, nil, nil, INVISIBLE)
  menubar.add("check",     nil, nil, nil, TOGGLE | VALUE)
  menubar.add("box",       nil, nil, nil, TOGGLE)
  win.show
end

FLTK.run
