#!/usr/bin/env ruby

# Copyright (C) 2008, 2009 Jeremy Henty.

# This file is part of Ruby-FFI-FLTK1.

# Ruby-FFI-FLTK1 is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Ruby-FFI-FLTK1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


$VERBOSE = true

require "rubygems"
require "ffi/fltk1"

include FFI
include FFI::FLTK

Window.new(300, 300, "Packs") do |win|
  size = 25
  label = 1
  pack_types = [ Pack::Type::VERTICAL, Pack::Type::HORIZONTAL ]
  position= [ 0, 0, win.w, win.h ]
  parent = win
  5.times do |count|
    parent.group_begin do
      Pack.new(*position) do |pack|
        (count + 1).times do |count1|
          Box.new(size, size, label).box(Box::Type::DOWN_BOX)
          label += 1
          position[count % 2] += size
          position[count % 2 + 2] -= size
        end
        pack.widget_type(pack_types[count % 2])
        parent.resizable(pack)
        parent = pack
      end
    end
  end
  win.size_range(1, 1, 0, 0)
  win.show
end

FLTK.run
